### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by ankitakanitkar** [rubypool/Weekly-Challenges#1]
Class Post < ActiveRecord::Base
    # Schema - Table posts
    # Colunms
    # :title , :string , null: false
    # :body, :text, null: false
    # :author, :string, null: false
end

Is there some issue with the following code? If Yes, what? If No, then how can we make it better?

post = Post.new do |p|
  p.title = "example"
  p.body = "An example"
end
post.save

**Comment by tusharmaroo** [comment]
We can have `save!` operator instead of `save`, so it will not skip validation and will be raising the error.

**Comment by ruby-rockers** [comment]
other than 2nd point above, It won't let you save this as 'author' value is missing and which is not null.

**Comment by SaurabhPandit89** [comment]
We can certainly make the code snippet more readable as shown below : 

```
post = Post.new({ title: 'Example', body: 'An Example', author: 'Sample Author'})
post.save!
```

**Comment by ankitakanitkar** [comment]
Sorry Guys Posts.new is a typo and not the real issue.. Updating it

**Comment by tsavani** [comment]
Less code and more readable :

```
Post.create!({ title: 'Example', body: 'An Example', author: 'Sample Author'})
```

:pray:

**Comment by nikitasingh** [comment]
Who is commenting with ruby-rockers ? :/

**Comment by nikitasingh** [comment]
```
post = Post.new({ title: 'Title', body: 'Body''})
begin
  post.save (or post.save!)
rescue Exception => e
  do something
end
```

save or save! both will raise exception in the case when any of the value is null, so it should be handled.

**Comment by ektaverma1** [comment]
+1 for @nikitasingh answer. Since the 'author' value is missing, we would need to handle the exception raised.

**Comment by tsavani** [comment]
Agree, but 'author' value is missing which is mandatory field so it will raised error each time instead of saving that record.

correct me if wrong.!!!

**Comment by nikitasingh** [comment]
@twinks14 yes, and that's why I think it should be handled.

**Comment by ankitakanitkar** [comment]
Well I'm thrilled to see the responses. We can find out so many ways of doing the same thing. All of you are correct in some way or the other. But the message I wanted to convey here was regarding the usage of save and save!. So in the example I gave, save is just going to fail silently by just returning false. So ideally you should either check for the return value of save or use save! instead.

**Comment by ankit8898** [comment]
👍 great going guys!

**Comment by ankitakanitkar** [comment]
arey gupta jee... aap kahaan :grin:

**Comment by nikitasingh** [comment]
Thank you @ankitakanitkar for giving us our first challenge. :)
Apart from this, just want to highlight that if we have put some database validations in the migration like null: false. It will throw exception even if just do save.
