### ISSUE TITLE
Challenge 2

### ISSUE THREAD

**Issue by ektaverma1** [rubypool/Weekly-Challenges#2]
What’s the issue with the controller code below ?How would you fix it?

```
class CommentsController < ApplicationController
  def users_comments
    posts = Post.all
    comments = posts.map(&:comments).flatten
    @user_comments = comments.select do |comment|
      comment.author.username == params[:username]
    end
  end
end
```

Addition info: 
Post has_many comments
Comment belongs_to author
Author has_many comments

**Comment by ankitakanitkar** [comment]
Is there any kind of association defined between posts comments and users?

**Comment by ghost** [comment]
``` ruby
class CommentsController < ApplicationController
  def index
    if params[:username]
     author = Author.where("username = ?", params[:username])
     @comments = author.comments
    #redundant as per question, but we might require 'elsif' if we use :index ;)
    elsif params[:post_id]
     @comments = Comment.where("post_id = ?", params[:post_id])
   end 
 end
end
```

**Comment by Arpit1989** [comment]
``` ruby
class CommentsController < ApplicationController
  def users_comments
    @user_comments = Comments.find_by_sql("select c.* from comments c where c.author_id  IN (select id from authors a where a.username = ?)",params[:username])
  end
end
```

**Comment by ektaverma1** [comment]
Thanks @himaenshu and @Arpit1989 for your answers.

This is a classic example of the notorious **“n+1”** bug. The first line will retrieve all of the Post objects from the database, but then the very next line will make an additional request for each Post to retrieve the corresponding Comment objects. To make matters worse, this code is then making even more database requests in order to retrieve the Author of each Comment.

This can all be avoided by changing the first line in the method to:

`posts = Post.includes(comments: [:author]).all`

This tells ActiveRecord to retrieve the corresponding Comment and Author records from the database immediately after the initial request for all Posts, thereby reducing the number of database requests to just three.

Please note that the above answer is only one of a few ways that it is possible to avoid incurring an “n+1” penalty.
