### ISSUE TITLE
Challenge 3

### ISSUE THREAD

**Issue by karanarora** [rubypool/Weekly-Challenges#3]
salary = {karan: 50, ankita: 1500000, ekta: 500000 }
sort the hash by value in descending order.

**Comment by AasthaKesarwani1539** [comment]
We can sort it by value in descending order by => `Hash[salary.sort_by{|key, value| value}.reverse]`

**Comment by ankitakanitkar** [comment]
sort in descending order of key or value?

**Comment by SaurabhPandit89** [comment]
We can make the @AasthaKesarwani1539 code more efficient to sort the hash in descending order by value, as shown below:

```
Hash[salary.sort_by{|key, value| -value}]
```

In above code, we got rid of `reverse` which was adding extra iteration.

**Comment by karanarora** [comment]
@ankitakanitkar value.

**Comment by ankitakanitkar** [comment]
sry @karanarora I missed reading value in your challenge statement itself

**Comment by karanarora** [comment]
np

**Comment by AasthaKesarwani1539** [comment]
I did not know that @SaurabhPandit89 Thanks !! :+1:

**Comment by ashish-sjc** [comment]
`salary.sort_by {|k,v| v}.reverse`

This is much better than 

`salary.sort_by {|k,v| -v}`

Refer http://stackoverflow.com/questions/4264133/descending-sort-by-value-of-a-hash-in-ruby

**Comment by karanarora** [comment]
thanks for sharing the benchmarks @ashish-sjc 
Thanks everyone for participating , this is what i would do too-
`salary.sort_by {|k,v| v}.reverse`
